@extends('layouts.app')
@section('content')
<div class="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p class="eyebrow">{{ __('common.overview') }}</p><h1 class="page-title">{{ __('common.dashboard') }}</h1><p class="page-subtitle">{{ __('common.dashboard_subtitle') }}</p></div><a href="{{ route('complaints.create') }}" class="btn-primary">{{ __('common.new_complaint') }}</a></div>
<div class="grid gap-6 lg:grid-cols-3">
<div class="card lg:col-span-2"><h2 class="section-title">{{ __('common.last_7_days') }}</h2><div class="mt-6 grid grid-cols-7 gap-2 items-end h-44">@php($max=max(1,$days->max())) @foreach($days as $date=>$total)<div class="flex h-full flex-col items-center justify-end gap-2"><span class="text-sm font-semibold">{{ $total }}</span><div class="w-full rounded-t bg-indigo-500" style="height:{{ max(8,($total/$max)*100) }}%"></div><span class="text-xs text-slate-500">{{ \Carbon\Carbon::parse($date)->translatedFormat('D') }}</span></div>@endforeach</div></div>
<div class="card"><h2 class="section-title">{{ __('common.most_complained_branches') }}</h2><div class="mt-5 space-y-4">@forelse($branches as $branch)<div class="flex justify-between"><span>{{ $branch->name }}</span><strong>{{ $branch->complaints_count }}</strong></div>@empty<p class="empty">{{ __('common.no_data') }}</p>@endforelse</div></div>
<div class="card"><h2 class="section-title">{{ __('common.status_distribution') }}</h2><div class="mt-5 space-y-3">@forelse($statuses as $status)<div class="flex items-center justify-between"><span class="badge" style="--badge-color:{{ $status->color }}">{{ $status->name }}</span><strong>{{ $status->complaints_count }}</strong></div>@empty<p class="empty">{{ __('common.no_data') }}</p>@endforelse</div></div>
<div class="card"><h2 class="section-title">{{ __('common.priority_distribution') }}</h2><div class="mt-5 space-y-3">@forelse($priorities as $priority)<div class="flex items-center justify-between"><span class="badge" style="--badge-color:{{ $priority->color }}">{{ $priority->name }}</span><strong>{{ $priority->complaints_count }}</strong></div>@empty<p class="empty">{{ __('common.no_data') }}</p>@endforelse</div></div>
</div>
@endsection
