@php($editing=isset($complaint))
@extends('layouts.app')
@section('content')
@php($selectedCustomer = $customer ?? ($complaint->customer ?? null))
@php($selectedCustomerId = old('customer_id', $selectedCustomer->id ?? ''))
<div class="mb-8"><a href="{{ $editing ? route('complaints.show',$complaint) : route('complaints.index') }}" class="back-link">← {{ __('common.back') }}</a><h1 class="page-title mt-4">{{ $editing ? __('common.edit_complaint') : __('common.new_complaint') }}</h1><p class="page-subtitle">{{ $customer->name ?? $complaint->customer->name ?? __('common.select_customer') }}</p></div>
<form method="POST" action="{{ $editing ? route('complaints.update',$complaint) : route('complaints.store') }}" class="card space-y-6">@csrf @if($editing) @method('PUT') @endif
<div class="rounded-xl border border-indigo-100 bg-indigo-50/60 p-4" data-customer-picker data-search-url="{{ route('customers.search') }}" data-empty-text="{{ __('common.no_customer_matches') }}"><label class="form-label">{{ __('common.customer') }} *</label><input type="hidden" name="customer_id" id="customer_id" value="{{ $selectedCustomerId }}" required><input type="search" id="customer-search" class="form-input" autocomplete="off" placeholder="{{ __('common.search_customers') }}"><p id="selected-customer" class="mt-2 text-sm font-semibold text-indigo-700 {{ $selectedCustomer ? '' : 'hidden' }}">{{ $selectedCustomer ? $selectedCustomer->name.' — '.$selectedCustomer->phone_primary : '' }}</p><div id="customer-results" class="mt-3 max-h-72 space-y-1 overflow-y-auto rounded-lg border border-slate-200 bg-white p-1">@if($data['customers']->isEmpty())<p class="px-3 py-3 text-sm text-slate-500">{{ __('common.no_customer_matches') }}</p>@endif @foreach($data['customers'] as $customerOption)<button type="button" class="customer-option flex w-full items-center justify-between rounded-md px-3 py-2 text-start text-sm hover:bg-indigo-50" data-id="{{ $customerOption->id }}" data-name="{{ $customerOption->name }}" data-phone="{{ $customerOption->phone_primary }}"><span class="font-medium">{{ $customerOption->name }}</span><span class="text-xs text-slate-500">{{ $customerOption->phone_primary }}</span></button>@endforeach</div><p class="mt-2 text-xs text-slate-600">{{ __('common.customer_required_help') }}</p></div>
<div class="grid gap-5 md:grid-cols-2 lg:grid-cols-4">@foreach(['branch_id'=>'branches','service_id'=>'services','source_id'=>'sources','category_id'=>'categories','type_id'=>'types','priority_id'=>'priorities','status_id'=>'statuses'] as $field=>$key)<div><label class="form-label">{{ __('common.'.str_replace('_id','',$field)) }} *</label><select class="form-input" required name="{{ $field }}"><option value="">{{ __('common.select') }}</option>@foreach($data[$key] as $item)<option value="{{ $item->id }}" @selected(old($field,$complaint->$field??'')==$item->id)>{{ $item->name }}</option>@endforeach</select></div>@endforeach<div><label class="form-label">{{ __('common.complaint_date') }} *</label><input class="form-input" type="date" required name="complaint_date" value="{{ old('complaint_date',optional($complaint->complaint_date ?? null)->format('Y-m-d') ?? now()->format('Y-m-d')) }}"></div></div>
<div><label class="form-label">{{ __('common.short_description') }} *</label><input class="form-input" required name="short_description" value="{{ old('short_description',$complaint->short_description??'') }}"></div><div><label class="form-label">{{ __('common.description') }} *</label><textarea class="form-input" required rows="6" name="description">{{ old('description',$complaint->description??'') }}</textarea></div><div><label class="form-label">{{ __('common.resolution') }}</label><textarea class="form-input" rows="4" name="resolution">{{ old('resolution',$complaint->resolution??'') }}</textarea></div>@if($editing)<div><label class="form-label">{{ __('common.status_reason') }}</label><input class="form-input" name="status_reason" placeholder="{{ __('common.status_reason_hint') }}"></div>@endif
<div class="flex justify-end gap-3"><a class="btn-secondary" href="{{ $editing ? route('complaints.show',$complaint) : route('complaints.index') }}">{{ __('common.cancel') }}</a><button class="btn-primary">{{ __('common.save') }}</button></div>
</form>
@endsection
