<?php
namespace App\Http\Controllers;
use App\Exports\ComplaintsExport;
use App\Http\Requests\{ComplaintFilterRequest,StoreComplaintRequest,UpdateComplaintRequest};
use App\Models\{Complaint,Customer,Branch,Service,ComplaintSource,ComplaintCategory,ComplaintType,Priority,ComplaintStatus,User};
use App\Services\{ActivityLogService,ComplaintStatusService};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Maatwebsite\Excel\Facades\Excel;
class ComplaintController extends Controller
{
    public function index(ComplaintFilterRequest $request) { abort_unless(auth()->user()?->can('complaint.view'), 403); $filters = $request->validated(); $complaints = Complaint::with(['customer','branch','service','category','type','priority','status','creator'])->filter($filters)->latest('complaint_date')->latest()->paginate(30)->withQueryString(); $data = $this->masterData(false, $filters['customer_id'] ?? null, $filters['branch_ids'] ?? []); return view('complaints.index', compact('complaints','filters','data')); }
    public function searchBranches(Request $request) { abort_unless(auth()->user()?->can('complaint.view') || auth()->user()?->can('report.view'), 403); $term = trim((string) $request->input('q')); $rows = Branch::query()->when($term !== '', fn($q) => $q->where(fn($x) => $x->where('name_en','like',"%$term%")->orWhere('name_ar','like',"%$term%")))->orderBy('sort_order')->orderBy('name_en')->get(['id','name_en','name_ar']); return response()->json($rows->map(fn ($branch) => ['id' => $branch->id, 'name' => $branch->localized_name])); }
    public function create(Request $request) { abort_unless(auth()->user()?->can('complaint.create'), 403); $customer = $request->filled('customer') ? Customer::findOrFail($request->integer('customer')) : null; $data = $this->masterData(true); return view('complaints.create', compact('customer','data')); }
    public function store(StoreComplaintRequest $request) { $values = $request->validated(); $type = $request->type(); $values['category_id'] = $type->category_id; $values['priority_id'] = $type->priority_id; $values['created_by'] = auth()->id(); $complaint = DB::transaction(function() use ($values) { $complaint = Complaint::create($values); app(ActivityLogService::class)->record('complaint.created',$complaint,__('complaints.created_log')); return $complaint; }); return redirect()->route('complaints.show',$complaint)->with('success',__('complaints.created')); }
    public function show(Complaint $complaint) { abort_unless(auth()->user()?->can('complaint.view'), 403); $complaint->load(['customer','branch','service','source','category','type','priority','status','creator','resolver','statusHistories.fromStatus','statusHistories.toStatus','statusHistories.changer','activityLogs.user']); return view('complaints.show', compact('complaint')); }
    public function edit(Complaint $complaint) { abort_unless(auth()->user()?->can('complaint.update'), 403); $complaint->load('customer'); $data = $this->masterData(true); return view('complaints.edit', compact('complaint','data')); }
    public function update(UpdateComplaintRequest $request, Complaint $complaint) { $values = $request->validated(); if ((int) ($values['type_id'] ?? 0) !== (int) $complaint->type_id) { $type = $request->type(); $values['category_id'] = $type->category_id; $values['priority_id'] = $type->priority_id; } $old = $complaint->only(array_keys($values)); $statusId = (int) $values['status_id']; $statusChanged = (int) $complaint->status_id !== $statusId; DB::transaction(function() use ($complaint,$values,$old,$statusChanged,$statusId) { if ($statusChanged) unset($values['status_id']); $complaint->update($values); app(ActivityLogService::class)->record('complaint.updated',$complaint,__('complaints.updated_log'),$old,$complaint->only(array_keys($values))); if ($statusChanged) app(ComplaintStatusService::class)->change($complaint,$statusId,request('status_reason')); }); return redirect()->route('complaints.show',$complaint)->with('success',__('complaints.updated')); }
    public function export(ComplaintFilterRequest $request) { abort_unless(auth()->user()->can('complaint.export'),403); return Excel::download(new ComplaintsExport($request->validated()), 'complaints-'.now()->format('Y-m-d').'.xlsx'); }
    private function masterData(bool $activeOnly = false, ?int $selectedCustomerId = null, array $selectedBranchIds = []): array { $scope = fn($model) => $model::query()->when($activeOnly, fn($q) => $q->where('is_active',true))->orderBy('sort_order')->orderBy('name_en')->get(); $customers = Customer::orderBy('name')->limit(10)->get(); $branches = Branch::query()->when($activeOnly, fn($q) => $q->where('is_active',true))->orderBy('sort_order')->orderBy('name_en')->get(); if ($selectedCustomerId && !$customers->contains('id', $selectedCustomerId)) { $selected = Customer::find($selectedCustomerId); if ($selected) $customers->push($selected); } return ['customers'=>$customers,'branches'=>$branches,'services'=>$scope(Service::class),'sources'=>$scope(ComplaintSource::class),'categories'=>$scope(ComplaintCategory::class),'types'=>ComplaintType::query()->with(['category','priority'])->when($activeOnly, fn($q) => $q->where('is_active',true))->orderBy('sort_order')->orderBy('name_en')->get(),'priorities'=>$scope(Priority::class),'statuses'=>$scope(ComplaintStatus::class),'users'=>User::orderBy('name')->get()]; }
}
